import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SocketProvider } from "~/app/_components/socket-provider";
import { api, HydrateClient } from "~/trpc/server";
import Header from "~/app/_components/header";
import { SessionProvider } from "~/app/_components/session-provider";
import { getUserSession } from "../../utils/auth-actions";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const posts = await api.post.getAllLatest();
  await api.auth.getMyPermissions.prefetch();
  const session = await getUserSession();

  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <SessionProvider session={session}>
            <SocketProvider initialPosts={posts}>
              <HydrateClient>
                <Header />
              </HydrateClient>
              {children}
            </SocketProvider>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
