import "~/styles/globals.css";

import {type Metadata} from "next";
import {Geist} from "next/font/google";

import {TRPCReactProvider} from "~/trpc/react";
import {SocketProvider} from "~/app/_components/socket-provider";
import {api} from "~/trpc/server";
import Header from "~/app/_components/header";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {

    const posts = await api.post.getAllLatest()

    return (
        <html lang="en" className={`${geist.variable}`}>
        <body>
        <TRPCReactProvider>
            <SocketProvider initialPosts={posts}>
                <Header/>
                {children}
            </SocketProvider>
        </TRPCReactProvider>
        </body>
        </html>
    );
}
